org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.251
neo_version_range=[21.1,)

## Mod Properties
mod_id=key_panel
mod_name=SimpleQuickKeys
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.trop.keypanel
mod_authors=TrZeal
mod_description=FTB 风格快捷功能面板（纯客户端，NeoForge 1.21.1）
